// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// KeyLineDefinition key line definition
//
// swagger:model KeyLineDefinition
type KeyLineDefinition struct {

	// kl
	Kl []*KeyLineSelection `json:"kl"`
}

// Validate validates this key line definition
func (m *KeyLineDefinition) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateKl(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *KeyLineDefinition) validateKl(formats strfmt.Registry) error {
	if swag.IsZero(m.Kl) { // not required
		return nil
	}

	for i := 0; i < len(m.Kl); i++ {
		if swag.IsZero(m.Kl[i]) { // not required
			continue
		}

		if m.Kl[i] != nil {
			if err := m.Kl[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("kl" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this key line definition based on the context it is used
func (m *KeyLineDefinition) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateKl(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *KeyLineDefinition) contextValidateKl(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Kl); i++ {

		if m.Kl[i] != nil {
			if err := m.Kl[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("kl" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *KeyLineDefinition) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *KeyLineDefinition) UnmarshalBinary(b []byte) error {
	var res KeyLineDefinition
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
