// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// MarketDataFilter market data filter
//
// swagger:model MarketDataFilter
type MarketDataFilter struct {

	// fields
	Fields []string `json:"fields"`

	// ladder levels
	LadderLevels int32 `json:"ladderLevels,omitempty"`
}

// Validate validates this market data filter
func (m *MarketDataFilter) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateFields(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var marketDataFilterFieldsItemsEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["EX_BEST_OFFERS_DISP","EX_BEST_OFFERS","EX_ALL_OFFERS","EX_TRADED","EX_TRADED_VOL","EX_LTP","EX_MARKET_DEF","SP_TRADED","SP_PROJECTED"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		marketDataFilterFieldsItemsEnum = append(marketDataFilterFieldsItemsEnum, v)
	}
}

func (m *MarketDataFilter) validateFieldsItemsEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, marketDataFilterFieldsItemsEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *MarketDataFilter) validateFields(formats strfmt.Registry) error {
	if swag.IsZero(m.Fields) { // not required
		return nil
	}

	for i := 0; i < len(m.Fields); i++ {

		// value enum
		if err := m.validateFieldsItemsEnum("fields"+"."+strconv.Itoa(i), "body", m.Fields[i]); err != nil {
			return err
		}

	}

	return nil
}

// ContextValidate validates this market data filter based on context it is used
func (m *MarketDataFilter) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *MarketDataFilter) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *MarketDataFilter) UnmarshalBinary(b []byte) error {
	var res MarketDataFilter
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
