// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// OrderMarketChange order market change
//
// swagger:model OrderMarketChange
type OrderMarketChange struct {

	// account Id
	AccountID int64 `json:"accountId,omitempty"`

	// closed
	Closed bool `json:"closed,omitempty"`

	// full image
	FullImage bool `json:"fullImage,omitempty"`

	// Market Id - the id of the market the order is on
	ID string `json:"id,omitempty"`

	// Order Changes - a list of changes to orders on a selection
	Orc []*OrderRunnerChange `json:"orc"`
}

// Validate validates this order market change
func (m *OrderMarketChange) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateOrc(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *OrderMarketChange) validateOrc(formats strfmt.Registry) error {
	if swag.IsZero(m.Orc) { // not required
		return nil
	}

	for i := 0; i < len(m.Orc); i++ {
		if swag.IsZero(m.Orc[i]) { // not required
			continue
		}

		if m.Orc[i] != nil {
			if err := m.Orc[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("orc" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this order market change based on the context it is used
func (m *OrderMarketChange) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateOrc(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *OrderMarketChange) contextValidateOrc(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Orc); i++ {

		if m.Orc[i] != nil {
			if err := m.Orc[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("orc" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *OrderMarketChange) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *OrderMarketChange) UnmarshalBinary(b []byte) error {
	var res OrderMarketChange
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
